### LOCAL Get api-docs
GET http://localhost:8080/api-docs

### Get All Appointments
GET http://localhost:8080/appointments

### Create new Appointment
POST http://localhost:8080/appointments HTTP/1.1
content-type: application/json

{
  "user":"jrock",
  "veterinarian":"Dr. Kelly Parnell", 
  "dateAndTime":"June 20 10:00am", 
  "purpose":"vaccination shots"
}

### Delete Appointment - MUST UPDATE ID!!!
DELETE http://localhost:8080/appointments/65563b82b1818abe9c24f85f